In [ ]:
import pandas as pd

In [ ]:
data1 = pd.read_excel('/content/B 의류(15,826).xlsx') # 의류
data2 = pd.read_excel('/content/H 관광여가오락(4,949).xlsx') # 관광
data3 = pd.read_excel('/content/차량등록_최종본(0429).xlsx') # 차량

# 의류

In [ ]:
test = data1[['SPEAKER', 'SENTENCE']]
test = test[:14900]

In [ ]:
test['match'] = test.SPEAKER.eq(test.SPEAKER.shift()) # 화자 중복 여부
test['SUB'] = test.SENTENCE.shift(-1) # 대사 1행씩 땡기기
test["FULL"] = test["SENTENCE"].astype(str) + " " + test["SUB"].astype(str) # 원래 대사와 이후 대사 합치기

In [ ]:
idx = test[test['match']==True].index # 화자가 중복되는 인덱스
idx

Int64Index([    2,    17,    19,    89,    91,   170,   188,   190,   257,
              295,
            ...
            12131, 12701, 13233, 13656, 13727, 13789, 13790, 13798, 14447,
            14510],
           dtype='int64', length=298)

In [ ]:
idx = idx-1
for i in range(len(test)):
    if i in idx:
        test.loc[i, 'SENTENCE'] = test.loc[i].FULL # 화자가 중복되면 이전 대화+이후 대사로 교체

test.drop(idx+1, inplace=True) # 이후 대사 삭제
test = test[['SPEAKER', 'SENTENCE']]
test.reset_index(drop=True, inplace=True)

In [ ]:
Q_sample_data =  test[test['SPEAKER']=='고객']
Q_data = Q_sample_data['SENTENCE']
A_sample_data =  test[test['SPEAKER']=='점원']
A_data = A_sample_data['SENTENCE']
Q_data = Q_data.reset_index()
A_data = A_data.reset_index()
del Q_data['index']
del A_data['index']
QA_Data = pd.concat([Q_data,A_data],axis=1)
QA_Data.columns = ['Q','A']
QA_Data

                             Q                              A
0             신발은 여기 있는 게 다예요?  네 성인이나 아동 다 있어요 발 사이즈 몇 신으세요?
1                        230이요            편하게 신을 수 있는 거 찾으세요?
2         네 봄이니까 편하게 신을 수 있는 거   이런 건 어떠세요? 이런 거도 신발 무척 편하거든요
3                굽 좀 높은 거 없나요?      봄 상품은 아직 어른 제품이 많이 안나왔습니다
4                     언제 들어와요?                이번주 지나면 들어올 거예요
...                        ...                            ...
7296  블라우스나 티셔츠 같은거는 얼마부터 있어요?      대부분 블라우스는 팔만원이나 십만원대로 있어요
7297             이런 스카프는 얼마예요?                그 스카프는 팔만 오천원이요
7298               이런 옷은 얼마예요?               그 옷은 십이만 팔천 원이에요
7299           지금 봄옷은 이르지 않나요?                  지금 봄옷 입기 괜찮아요
7300          요즘 유행하는 색깔이 뭐예요?                요즘 파스텔 톤이 유행이에요

[7301 rows x 2 columns]

In [ ]:
QA_Data.to_excel('의류.xlsx')

# 관광

In [ ]:
test2 = data2[['SPEAKER', 'SENTENCE']]
test2 = test2[:4704]

In [ ]:
test2['match'] = test2.SPEAKER.eq(test2.SPEAKER.shift()) # 화자 중복 여부
idx = test2[test2['match']==True].index # 화자가 중복되는 인덱스
idx

Int64Index([617, 618, 4694, 4698], dtype='int64')

In [ ]:
test2.drop([616, 617], inplace=True)
test2.drop([4694,4695,4696,4697], inplace=True)
test2 = test2[['SPEAKER', 'SENTENCE']]
test2.reset_index(drop=True, inplace=True)

In [ ]:
Q_sample_data =  test2[test2['SPEAKER']=='고객']
Q_data = Q_sample_data['SENTENCE']
A_sample_data =  test2[test2['SPEAKER']=='점원']
A_data = A_sample_data['SENTENCE']
Q_data = Q_data.reset_index()
A_data = A_data.reset_index()
del Q_data['index']
del A_data['index']
QA_Data = pd.concat([Q_data,A_data],axis=1)
QA_Data.columns = ['Q','A']
QA_Data

                                       Q                                               A
0                            1시간에 얼마인가요?             처음 1시간은 1000원이고 이후 1시간은 500원씩 추가됩니다
1                             무인발급기 있나요?                      무인발급기는 카운터 바로 옆쪽에 이용 가능합니다
2                       1달 정액권 끊을 수 있나요?                                   네 1달에 5만 원입니다
3                      정액권 끊다가 정지해도 되나요?                                         네 가능합니다
4                           음식 주문 가능한가요?                               햄버거랑 핫도그 종류 가능합니다
...                                  ...                                             ...
2344                수강료는 한 얼마쯤 하는가 그래서요?    돈은 전체적으로 서울이나 대구나 다 다르고, 선수 반은 매일 와야 하는 거거든요
2345             당구 배울려면, 당구장에 매일 와야 돼요?            그래야 진도가 빠르죠. 학교 갔다가 될 수 있으면 빨리 오면 좋죠
2346                     수강료 다 합하면 얼마에요?          주 일 회하면 삼십오만 원 정도고 주 이 회하면 사십오만원 정도 돼요
2347                수강하는데에 더 필요한 거는 없어요?  혼자 쓰는 개인 큐는 필요해요. 그거는 이제 부모님이 하나 장만해주던지 하시면 돼요
2348  제가 강습 받고 싶어하는 애를 데리고 한 번 나와봐야 되겠네요                                  그러세요. 데리고 나오세요

[2349 rows x 2 columns]

In [ ]:
QA_Data.to_excel('관광.xlsx')

# 차량

In [ ]:
data3 = pd.read_excel('/content/차량등록_최종본(0429).xlsx') # 차량
data3 = data3[['question', 'answer']]
data3.reset_index(drop=True)

                                               question                                             answer
0                                네 수고하십니다. 오늘 차량등록 됩니까?    어 오늘은 공휴일이라서 업무를 보지 않고 있고요 월요일부터 금요일까지 업무시간입니다.
1     어 삼십일일자까지 임시 남바 기간이면은 어떻게 해요 삼일동안 그냥 벌금내고 그냥 타...                        신규차량은 삼십일일까지였으면 공휴일 삼십일일까지요
2                           뭐 과태료는 삼일정도 같으면 얼마 정도 나옵니까?           어 십일이 지나고 나서 다시 또 십일 안에는 십일 이내에는 오만원입니다.
3                                     그니까 단속되면 어떻게 됩니까?                                         처분대상이 되겠지요
4                                           어떻게 처분이 되죠.  원래는 등록을 하셔야 되는데 단속이 되시면은 그거는 이제 경찰에서 단속을 하는 부분...
...                                                 ...                                                ...
3741                                        네 차번호 몇번입니까                                        네 #자동차번호#이요
3742                                공삼육삼번이고 차명은 어떻게 되세요                                         어 에스 삼오공이고
3743                  네 네 바로 확인 되셨구요 제작년도가 이천십사년식 맞으신가요                                                  네
3744  그 차량등록 관련해서요 그 제가 이제 어른이 예 장애인이고 면세 해당이 되셔서 장애...                       그런 경우는 본인세대가 아니면 등록자체가 불가합니다
3745           현재 선생님 그 장애등급이 있으신분께서 구매하는 차량이 엘피지 차량이세요                                             예 맞습니다

[3746 rows x 2 columns]

In [ ]:
data3[data3['question'].isnull()==True] # 1711

     question                        answer
1711      NaN  네 번호가 #전화번호#에서 #전화번호#번까지입니다.

In [ ]:
idx_null = data3[data3['answer'].isnull()==True].index
idx_null

Int64Index([  31,   62,  146,  147,  250,  380,  485,  530, 1266, 1345, 1372,
            1418, 1504, 1660, 1680, 1703, 1753, 1808, 1833, 1836, 1838, 1845,
            1893, 1924, 2020, 2071, 2074, 2075, 2079, 2083, 2135, 2143, 2171,
            2191, 2208, 2224, 2240, 2248, 2313, 2317, 2320, 2359, 2385, 2493,
            2581, 2620, 2641, 2644, 2729, 3019, 3036, 3444, 3487, 3574, 3652,
            3698, 3737],
           dtype='int64')

In [ ]:
data3.drop(idx_null, inplace=True)
data3.drop(1711, inplace=True)
data3.reset_index(drop=True)

                                               question                                             answer
0                                네 수고하십니다. 오늘 차량등록 됩니까?    어 오늘은 공휴일이라서 업무를 보지 않고 있고요 월요일부터 금요일까지 업무시간입니다.
1     어 삼십일일자까지 임시 남바 기간이면은 어떻게 해요 삼일동안 그냥 벌금내고 그냥 타...                        신규차량은 삼십일일까지였으면 공휴일 삼십일일까지요
2                           뭐 과태료는 삼일정도 같으면 얼마 정도 나옵니까?           어 십일이 지나고 나서 다시 또 십일 안에는 십일 이내에는 오만원입니다.
3                                     그니까 단속되면 어떻게 됩니까?                                         처분대상이 되겠지요
4                                           어떻게 처분이 되죠.  원래는 등록을 하셔야 되는데 단속이 되시면은 그거는 이제 경찰에서 단속을 하는 부분...
...                                                 ...                                                ...
3683                                        네 차번호 몇번입니까                                        네 #자동차번호#이요
3684                                공삼육삼번이고 차명은 어떻게 되세요                                         어 에스 삼오공이고
3685                  네 네 바로 확인 되셨구요 제작년도가 이천십사년식 맞으신가요                                                  네
3686  그 차량등록 관련해서요 그 제가 이제 어른이 예 장애인이고 면세 해당이 되셔서 장애...                       그런 경우는 본인세대가 아니면 등록자체가 불가합니다
3687           현재 선생님 그 장애등급이 있으신분께서 구매하는 차량이 엘피지 차량이세요                                             예 맞습니다

[3688 rows x 2 columns]

In [ ]:
data3.columns = ['Q','A']
data3

                                                      Q                                                  A
0                                네 수고하십니다. 오늘 차량등록 됩니까?    어 오늘은 공휴일이라서 업무를 보지 않고 있고요 월요일부터 금요일까지 업무시간입니다.
1     어 삼십일일자까지 임시 남바 기간이면은 어떻게 해요 삼일동안 그냥 벌금내고 그냥 타...                        신규차량은 삼십일일까지였으면 공휴일 삼십일일까지요
2                           뭐 과태료는 삼일정도 같으면 얼마 정도 나옵니까?           어 십일이 지나고 나서 다시 또 십일 안에는 십일 이내에는 오만원입니다.
3                                     그니까 단속되면 어떻게 됩니까?                                         처분대상이 되겠지요
4                                           어떻게 처분이 되죠.  원래는 등록을 하셔야 되는데 단속이 되시면은 그거는 이제 경찰에서 단속을 하는 부분...
...                                                 ...                                                ...
3741                                        네 차번호 몇번입니까                                        네 #자동차번호#이요
3742                                공삼육삼번이고 차명은 어떻게 되세요                                         어 에스 삼오공이고
3743                  네 네 바로 확인 되셨구요 제작년도가 이천십사년식 맞으신가요                                                  네
3744  그 차량등록 관련해서요 그 제가 이제 어른이 예 장애인이고 면세 해당이 되셔서 장애...                       그런 경우는 본인세대가 아니면 등록자체가 불가합니다
3745           현재 선생님 그 장애등급이 있으신분께서 구매하는 차량이 엘피지 차량이세요                                             예 맞습니다

[3688 rows x 2 columns]

In [ ]:
data3.to_excel('차량.xlsx')

# CONCAT

In [ ]:
import os
 
path_dir = '/content/'
file_list = os.listdir(path_dir)

In [ ]:
file_list = file_list[1:-1]
file_list

['음식점_배달음식점.csv',
 '부동산_상가.csv',
 '상수도.csv',
 '관광여가오락_pc방.csv',
 '숙박업_호텔.csv',
 '숙박업_펜션캠핑장.csv',
 '생활서비스_세탁소1.csv',
 '의류_액세서리.csv',
 '.ipynb_checkpoints',
 '소매점_떡집.csv',
 '학원_미술학원.csv',
 '숙박업_모텔여관.csv',
 '학원_영수학원.csv',
 '소매점_반찬가게.csv',
 '생활서비스_미용실.csv',
 '생활서비스_옷수선.csv',
 '생활서비스_세탁소2.csv',
 '소매점_화장품.csv',
 '의류_가방.csv',
 '의류_의류.csv',
 '차량.xlsx',
 '학원_피아노.csv',
 '소매점_청과물.csv',
 '교통.csv',
 '생활서비스_독서실.csv',
 '학원_어학원.csv',
 '음식점_홀서빙음식점.csv',
 '생활서비스_약국.csv',
 '의류_신발.csv',
 '관광여가오락_당구장.csv',
 '카페.csv',
 '부동산_토지.csv',
 '학원_태권도.csv',
 '부동산_주택.csv',
 '여권.csv',
 '소매점_제과점.csv',
 '음식점_셀프서비스.csv',
 '소매점_정육점.csv']

In [ ]:
pd.read_csv('')

In [ ]:
file_list = file_list[1:]

df = pd.read_csv('/content/음식점_배달음식점.csv', index_col = [0])

for i in file_list:
    df_temp = pd.read_csv(f'/content/{i}', index_col = [0])
    df = pd.concat([df, df_temp], axis = 'rows', ignore_index=True)

ParserError: ignored

In [ ]:
for i, j in enumerate(file_list):
    print(i, j)
    data_'{}' = pd.read_csv('/content/{}')

0 음식점_배달음식점.csv